// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: config/configpb/config.proto

package configpb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// DeepCopyInto supports using ResourceRequest within kubernetes types, where deepcopy-gen is used.
func (in *ResourceRequest) DeepCopyInto(out *ResourceRequest) {
	p := proto.Clone(in).(*ResourceRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRequest. Required by controller-gen.
func (in *ResourceRequest) DeepCopy() *ResourceRequest {
	if in == nil {
		return nil
	}
	out := new(ResourceRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRequest. Required by controller-gen.
func (in *ResourceRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ResourceReply within kubernetes types, where deepcopy-gen is used.
func (in *ResourceReply) DeepCopyInto(out *ResourceReply) {
	p := proto.Clone(in).(*ResourceReply)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceReply. Required by controller-gen.
func (in *ResourceReply) DeepCopy() *ResourceReply {
	if in == nil {
		return nil
	}
	out := new(ResourceReply)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ResourceReply. Required by controller-gen.
func (in *ResourceReply) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ConfigRequest within kubernetes types, where deepcopy-gen is used.
func (in *ConfigRequest) DeepCopyInto(out *ConfigRequest) {
	p := proto.Clone(in).(*ConfigRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigRequest. Required by controller-gen.
func (in *ConfigRequest) DeepCopy() *ConfigRequest {
	if in == nil {
		return nil
	}
	out := new(ConfigRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ConfigRequest. Required by controller-gen.
func (in *ConfigRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ConfigReply within kubernetes types, where deepcopy-gen is used.
func (in *ConfigReply) DeepCopyInto(out *ConfigReply) {
	p := proto.Clone(in).(*ConfigReply)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigReply. Required by controller-gen.
func (in *ConfigReply) DeepCopy() *ConfigReply {
	if in == nil {
		return nil
	}
	out := new(ConfigReply)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ConfigReply. Required by controller-gen.
func (in *ConfigReply) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Request within kubernetes types, where deepcopy-gen is used.
func (in *Request) DeepCopyInto(out *Request) {
	p := proto.Clone(in).(*Request)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Request. Required by controller-gen.
func (in *Request) DeepCopy() *Request {
	if in == nil {
		return nil
	}
	out := new(Request)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Request. Required by controller-gen.
func (in *Request) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ResourceKey within kubernetes types, where deepcopy-gen is used.
func (in *ResourceKey) DeepCopyInto(out *ResourceKey) {
	p := proto.Clone(in).(*ResourceKey)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceKey. Required by controller-gen.
func (in *ResourceKey) DeepCopy() *ResourceKey {
	if in == nil {
		return nil
	}
	out := new(ResourceKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ResourceKey. Required by controller-gen.
func (in *ResourceKey) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Reply within kubernetes types, where deepcopy-gen is used.
func (in *Reply) DeepCopyInto(out *Reply) {
	p := proto.Clone(in).(*Reply)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Reply. Required by controller-gen.
func (in *Reply) DeepCopy() *Reply {
	if in == nil {
		return nil
	}
	out := new(Reply)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Reply. Required by controller-gen.
func (in *Reply) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Status within kubernetes types, where deepcopy-gen is used.
func (in *Status) DeepCopyInto(out *Status) {
	p := proto.Clone(in).(*Status)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Status. Required by controller-gen.
func (in *Status) DeepCopy() *Status {
	if in == nil {
		return nil
	}
	out := new(Status)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Status. Required by controller-gen.
func (in *Status) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Deviation within kubernetes types, where deepcopy-gen is used.
func (in *Deviation) DeepCopyInto(out *Deviation) {
	p := proto.Clone(in).(*Deviation)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Deviation. Required by controller-gen.
func (in *Deviation) DeepCopy() *Deviation {
	if in == nil {
		return nil
	}
	out := new(Deviation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Deviation. Required by controller-gen.
func (in *Deviation) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Path within kubernetes types, where deepcopy-gen is used.
func (in *Path) DeepCopyInto(out *Path) {
	p := proto.Clone(in).(*Path)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Path. Required by controller-gen.
func (in *Path) DeepCopy() *Path {
	if in == nil {
		return nil
	}
	out := new(Path)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Path. Required by controller-gen.
func (in *Path) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using PathElem within kubernetes types, where deepcopy-gen is used.
func (in *PathElem) DeepCopyInto(out *PathElem) {
	p := proto.Clone(in).(*PathElem)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PathElem. Required by controller-gen.
func (in *PathElem) DeepCopy() *PathElem {
	if in == nil {
		return nil
	}
	out := new(PathElem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new PathElem. Required by controller-gen.
func (in *PathElem) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
